# Generated by Django 4.2.7 on 2023-11-12 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_pat', models.CharField(max_length=50)),
                ('ap_mat', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
                ('status', models.SmallIntegerField()),
                ('contacto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alu_19280725.contacto')),
            ],
        ),
    ]
