# Generated by Django 4.2.7 on 2023-11-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alu_19280725', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Contactos',
        ),
    ]
