# Generated by Django 4.2.7 on 2023-11-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alu_19280725', '0002_rename_contacto_contactos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='contacto_id',
            new_name='contacto',
        ),
    ]
